name: Build
on: [push]
jobs:
  build:
    if: github.repository != 'tmfg/digitraffic-common'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Compile
        run: |
          pnpm install
          pnpm build

      - name: Run tests
        run: |
          pnpm test >> $GITHUB_STEP_SUMMARY

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Jest test report
          reporter: jest-junit
          path: junit.xml

      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: FAILED digitraffic-common build
          fields: repo, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
