name: ESLint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install packages
        run: yarn install --frozen-lock

      - name: Create ESLint reports for affected projects
        id: report
        run: yarn eslint-report -- -o ${{ github.ref_name }}/report.html
        continue-on-error: true

      - name: Publish report
        id: publish-reports
        uses: tmfg/digitraffic-actions@gh-pages-publish/v1
        with:
          GH_PAGES_BRANCH: gh-pages
          FILE_PATH: ${{ github.ref_name }}/report.html
          COMMIT_MESSAGE: ESLint report in branch $CURRENT_BRANCH
          LINK_TEXT: ESLint report

      - name: Fail on ESLint errors
        run: |
          if [[ "${{ steps.report.outcome }}" == "failure" || "${{ steps.report-affected.outcome }}" == "failure" ]]; then exit 1; else exit 0; fi
