name: Publish Package to Github Packages
on:
  release:
    types: [created]
  push:
    branches:
      - 'feature/**'
jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
      - run: sed -i 's#tmfg/digitraffic-common#'${{ github.repository }}'#g' package.json
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn publish --tag ${{ GITHUB_REF }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
